### ISSUE TITLE
[Bug] Workflow "initial step" fails due to permission problem

### ISSUE THREAD

**Issue by oliverklee** [skills/template-template#25] opened 2023-01-11 12:28 UTC
**Describe the bug**

**To Reproduce**
1. Create a new repository from this template.
2. Click on the "Actions" tab of the new repository.
3. Check the "On start" workflow

**Screenshots**
![grafik](https://user-images.githubusercontent.com/765746/211806442-9155cc2e-9fd4-40b2-bfa4-e601e4ff947e.png)

**Comment by sinsukehlab** [comment] 2023-02-14 10:48
Duplicate of skills/resolve-merge-conflicts#7

**Comment by heiskr** [comment] 2023-02-16 05:32
Thank you for opening this issue. We've updated most of the courses to remove `gh pr create` to avoid this issue, including the merge conflicts course. Let us know if you encounter further errors.

**Closed by heiskr** 2023-02-16 05:32 UTC
Labels: bug
